/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Dashboard extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Dashboard1
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Football_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cricket_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Table_tennis_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Basketball_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Volleyball_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Back_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hamro Khelkud");
        setIconImage(new ImageIcon("src/View/photo/sports.png").getImage());

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("src/view/photo/dashboard/pk1.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 100, 100);

        Football_button.setForeground(new java.awt.Color(0, 0, 204));
        Football_button.setText("Football");
        Football_button.addActionListener(this);
        jPanel1.add(Football_button);
        Football_button.setBounds(10, 250, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("src/view/photo/dashboard/aw.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 120, 90, 90);

        Cricket_button.setForeground(new java.awt.Color(0, 0, 204));
        Cricket_button.setText("Cricket");
        jPanel1.add(Cricket_button);
        Cricket_button.setBounds(130, 250, 110, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("src/view/photo/dashboard/table_tennis.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 120, 110, 100);

        Table_tennis_button.setForeground(new java.awt.Color(0, 0, 204));
        Table_tennis_button.setText("Table Tennis");
        Table_tennis_button.addActionListener(this);
        jPanel1.add(Table_tennis_button);
        Table_tennis_button.setBounds(280, 250, 110, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("src/view/photo/dashboard/bk1.png")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 120, 100, 100);

        Basketball_button.setForeground(new java.awt.Color(0, 0, 204));
        Basketball_button.setText("Basketball");
        Basketball_button.addActionListener(this);

        Basketball_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(Basketball_button);
        Basketball_button.setBounds(430, 250, 110, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("src/view/photo/dashboard/ay.png")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 130, 100, 90);

        Volleyball_button.setForeground(new java.awt.Color(0, 0, 204));
        Volleyball_button.setText("Volleyball");
        Volleyball_button.addActionListener(this);
        jPanel1.add(Volleyball_button);
        Volleyball_button.setBounds(580, 250, 110, 30);

        jLabel7.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jLabel7.setText("HAMRO KHELKUD");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 30, 410, 60);

        Back_button.setBackground(new java.awt.Color(204, 204, 204));
        Back_button.setForeground(new java.awt.Color(0, 0, 255));
        Back_button.setText("Back");
        Back_button.addActionListener(this);

        jPanel1.add(Back_button);
        Back_button.setBounds(620, 10, 73, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("src/view/photo/dashboard/sports1.jfif")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -10, 710, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Football_button;
    private javax.swing.JButton Cricket_button;
    private javax.swing.JButton Table_tennis_button;
    private javax.swing.JButton Basketball_button;
    private javax.swing.JButton Volleyball_button;
    private javax.swing.JButton Back_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()== Volleyball_button){
            new Volleyball().setVisible(true);
            dispose();
        }
        if(e.getSource()== Back_button){
            new login().setVisible(true);
            dispose();
        }
        if(e.getSource()==Football_button){
            new football().setVisible(true);
            dispose();
        }
        if(e.getSource()== Table_tennis_button){
            new Table_tennis().setVisible(true);
            dispose();
        }
        if(e.getSource()== Basketball_button){
            new Dashboard().setVisible(true);
            dispose();
        }
        if(e.getSource()== Cricket_button){
            new Dashboard().setVisible(true);
            dispose();
        }
    }
    // End of variables declaration
}
